name: bh22_environment
channels:
  - conda-forge
dependencies:
  - python ==3.9
  - pip
  - scipy
  - numpy
  - pandas
  - h5py
  - seaborn
  - matplotlib-base
  - nilearn
  - nibabel
  - ipython
  - git
